const data = {
  0: {
    rating: 1,
    taskHeading: "Sample Task Heading",
    taskDesc: "Sample Task description ",
    manageRemark: "",
    empRemark: "",
    progress: 4,
  },
  1: {
    rating: 1,
    taskHeading: "Task Heading1",
    taskDesc: "Task description 1 ",
    manageRemark: "",
    empRemark: "",
    progress: 4,
  },
  2: {
    rating: 1,
    taskHeading: "Task Heading2",
    taskDesc: "Task description 2 ",
    manageRemark: "",
    empRemark: "",
    progress: 1,
  },
  3: {
    rating: 1,
    taskHeading: "Task Heading3",
    taskDesc: "Task description 3 ",
    manageRemark: "",
    empRemark: "",
    progress: 3,
  },
  4: {
    rating: 1,
    taskHeading: "Task Heading4",
    taskDesc: "Task description 4 ",
    manageRemark: "",
    empRemark: "",
    progress: 4,
  },
  5: {
    rating: 1,
    taskHeading: "Task Heading5",
    taskDesc: "Task description 5 ",
    manageRemark: "",
    empRemark: "",
    progress: 2,
  },
  6: {
    rating: 1,
    taskHeading: "Task Heading6",
    taskDesc: "Task description 6 ",
    manageRemark: "",
    empRemark: "",
    progress: 1,
  },
  7: {
    rating: 1,
    taskHeading: "Task Heading7",
    taskDesc: "Task description 7 ",
    manageRemark: "",
    empRemark: "",
    progress: 5,
  },
  8: {
    rating: 1,
    taskHeading: "Task Heading8",
    taskDesc: "Task description 8 ",
    manageRemark: "",
    empRemark: "",
    progress: 2,
  },
};

export default data;
